name: globe_trans_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/flags/flag_turkey.png
    - assets/flags/flag_usa.png
    - assets/flags/flag_germany.png
    - assets/flags/flag_france.png
    - assets/flags/flag_canada.png
    - assets/flags/flag_belgium.png
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sfpro/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/sfpro/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/sfpro/SFPRODISPLAYLIGHTITALIC.OTF
          weight: 300
          style: italic
        - asset: assets/fonts/sfpro/SFPRODISPLAYBOLD.OTF
