// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRG1swg67AnfZSJdOFYE4aqS3OmsjvVwQ',
    appId: '1:380969733195:ios:9bc5ace12763ff03a1d1ce',
    messagingSenderId: '380969733195',
    projectId: 'globetransmessage',
    storageBucket: 'globetransmessage.firebasestorage.app',
    iosClientId: '380969733195-miievqar994dopi44njse320fi7ho87l.apps.googleusercontent.com',
    iosBundleId: 'com.example.globeTransApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6AqvGJj7gdDtIHwa3R26tuGJYZqG78GU',
    appId: '1:380969733195:web:3e6a1dc74e9295dba1d1ce',
    messagingSenderId: '380969733195',
    projectId: 'globetransmessage',
    authDomain: 'globetransmessage.firebaseapp.com',
    storageBucket: 'globetransmessage.firebasestorage.app',
    measurementId: 'G-9GQBST38DE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRG1swg67AnfZSJdOFYE4aqS3OmsjvVwQ',
    appId: '1:380969733195:ios:9bc5ace12763ff03a1d1ce',
    messagingSenderId: '380969733195',
    projectId: 'globetransmessage',
    storageBucket: 'globetransmessage.firebasestorage.app',
    iosClientId: '380969733195-miievqar994dopi44njse320fi7ho87l.apps.googleusercontent.com',
    iosBundleId: 'com.example.globeTransApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm0pposjKiLeYqIH9axQxurp_0kri2ICA',
    appId: '1:380969733195:android:c1a08fe0c434dd6ba1d1ce',
    messagingSenderId: '380969733195',
    projectId: 'globetransmessage',
    storageBucket: 'globetransmessage.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6AqvGJj7gdDtIHwa3R26tuGJYZqG78GU',
    appId: '1:380969733195:web:de01ae057444223da1d1ce',
    messagingSenderId: '380969733195',
    projectId: 'globetransmessage',
    authDomain: 'globetransmessage.firebaseapp.com',
    storageBucket: 'globetransmessage.firebasestorage.app',
    measurementId: 'G-MNREB4Q5N5',
  );

}